### ISSUE TITLE
Misspell of Environment

### ISSUE THREAD

**Issue by cordovez** [didaquis/boilerplate-backend-node-graphql-mongodb#27]
Hello @didaquis ,
Recently I used your FRONT boilerplate code because my Apollo Client broke and I needed to a better way to create an Apollo Provider. So thank you very much, it saved me (after a lot of  😭 ).

In your _env file you have ENVIROMENT instead of ENVIRO**N**MENT. I see that you don't misspell the word in other parts. And the code works because you have used the misspelled word where needed.

When I was looking through my copy of your template, I came very close to correcting it in  thinking it was a single case (see line 39 of server.js). So perhaps it should be corrected or at the very least, pointed out so a new user doesn't break the connection by correcting it in the server.js file?

**Comment by didaquis** [comment]
Hello. 

First of all, thank you very much for writing this issue. You are right, there is a typo there! 

I will think of a way to fix it and try to correct that error. 

It is likely that no user will be affected, since this repository is after all a starter pack. Probably, when users use it they develop their own logic and don't bring back the upstream changes anymore. 

In any case, I'll take a closer look. 

Again, thank you very much for bringing this bug to my attention.

**Comment by didaquis** [comment]
This error has been solved. Thanks!

https://github.com/didaquis/boilerplate-backend-node-graphql-mongodb/releases/tag/v2.0.0
